import { LanguageCode } from './types';

export const SUPPORTED_LANGUAGES: { code: LanguageCode; name: string; flag: string }[] = [
  { code: 'ID', name: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'EN', name: 'English', flag: '🇺🇸' },
  { code: 'JP', name: '日本語 (Japanese)', flag: '🇯🇵' },
  { code: 'ES', name: 'Español', flag: '🇪🇸' },
  { code: 'DE', name: 'Deutsch', flag: '🇩🇪' },
];

export const STOIC_QUOTES: Record<LanguageCode, string[]> = {
  ID: [
    "Kamu memiliki kuasa atas pikiranmu - bukan kejadian di luar. - Marcus Aurelius",
    "Kita lebih sering menderita dalam imajinasi daripada dalam kenyataan. - Seneca",
    "Kebahagiaan hidupmu bergantung pada kualitas pikiranmu. - Marcus Aurelius",
    "Bukan apa yang terjadi padamu, tetapi bagaimana kamu bereaksi terhadapnya yang penting. - Epictetus",
  ],
  EN: [
    "You have power over your mind - not outside events. - Marcus Aurelius",
    "We suffer more often in imagination than in reality. - Seneca",
    "The happiness of your life depends upon the quality of your thoughts. - Marcus Aurelius",
    "It's not what happens to you, but how you react to it that matters. - Epictetus",
  ],
  JP: [
    "あなたの心に対する権力はあなたにある。外の出来事にはない。 - マルクス・アウレリウス",
    "私たちは現実よりも想像の中で苦しむことが多い。 - セネカ",
    "あなたの人生の幸福は、あなたの思考の質にかかっている。 - マルクス・アウレリウス",
    "重要なのは、何が起こるかではなく、それにどう反応するかだ。 - エピクテトス",
  ],
  ES: [
    "Tienes poder sobre tu mente, no sobre los acontecimientos externos. - Marco Aurelio",
    "Sufrimos más a menudo en la imaginación que en la realidad. - Séneca",
    "La felicidad de tu vida depende de la calidad de tus pensamientos. - Marco Aurelio",
    "No es lo que te pasa, sino cómo reaccionas a ello lo que importa. - Epicteto",
  ],
  DE: [
    "Du hast Macht über deinen Geist – nicht über äußere Ereignisse. - Marcus Aurelius",
    "Wir leiden öfter in der Einbildung als in der Wirklichkeit. - Seneca",
    "Das Glück deines Lebens hängt von der Beschaffenheit deiner Gedanken ab. - Marcus Aurelius",
    "Es kommt nicht darauf an, was dir widerfährt, sondern wie du darauf reagierst. - Epictetus",
  ]
};

export const UI_TEXT: Record<LanguageCode, any> = {
  ID: {
    splashSub: "Logika di atas Kekacauan",
    onboardingTitle: "Saya bukan teman curhat yang akan memanjakanmu.",
    onboardingDesc: "Saya di sini untuk melatih logikamu. Siap menghadapi kebenaran?",
    nameLabel: "Siapa namamu?",
    startBtn: "MULAI SESI STOIK",
    dashboardGreeting: "Halo, {name}.",
    dashboardPrompt: "Apa yang mengganggu pikiranmu?",
    inputPlaceholder: "Tuliskan kecemasanmu di sini... Jujurlah.",
    imgAttached: "Gambar terlampir",
    analyzeBtn: "ANALISA LOGIKA",
    worstCaseBtn: "Simulasi Skenario Terburuk",
    loading: "Marcus sedang berpikir...",
    resultTitle: "Analisis",
    filterTitle: "Filter Fakta",
    facts: "Fakta (Realita)",
    opinions: "Opini (Persepsi)",
    dichotomyTitle: "Dikotomi Kendali",
    inControl: "Dalam Kendalimu",
    outControl: "Di Luar Kendalimu",
    verdictTitle: "Vonis Marcus",
    debateBtn: "Debat Marcus",
    doneBtn: "Selesai",
    debateHeader: "Debat Stoik",
    debateOnline: "Marcus Online",
    debateEnd: "Akhiri",
    debatePlaceholder: "Tantang logika Marcus...",
    debateInit: "Vonis sudah dijatuhkan. Namun jika kamu masih ragu, katakanlah. Logika mana yang ingin kamu tantang?",
    error: "Marcus sedang diam. Periksa koneksi atau API key Anda lalu coba lagi."
  },
  EN: {
    splashSub: "Logic Over Chaos",
    onboardingTitle: "I am not a friend who will coddle you.",
    onboardingDesc: "I am here to train your logic. Are you ready to face the truth?",
    nameLabel: "What is your name?",
    startBtn: "BEGIN STOIC SESSION",
    dashboardGreeting: "Hello, {name}.",
    dashboardPrompt: "What is disturbing your peace of mind?",
    inputPlaceholder: "Write your anxiety here... Be honest.",
    imgAttached: "Image attached",
    analyzeBtn: "ANALYZE LOGIC",
    worstCaseBtn: "Simulate Worst Case",
    loading: "Marcus is thinking...",
    resultTitle: "The Analysis",
    filterTitle: "The Filter",
    facts: "Facts (Reality)",
    opinions: "Opinions (Perception)",
    dichotomyTitle: "Dichotomy of Control",
    inControl: "In Your Power",
    outControl: "Not In Your Power",
    verdictTitle: "Marcus' Verdict",
    debateBtn: "Debate Marcus",
    doneBtn: "Done",
    debateHeader: "Stoic Debate",
    debateOnline: "Marcus Online",
    debateEnd: "End Session",
    debatePlaceholder: "Challenge Marcus' logic...",
    debateInit: "The verdict is cast. But if you doubt, speak. Which logic do you wish to challenge?",
    error: "Marcus is silent. Check your connection or API key and try again."
  },
  JP: {
    splashSub: "混沌より論理を",
    onboardingTitle: "私はあなたを甘やかす友人ではない。",
    onboardingDesc: "私はあなたの論理を鍛えるためにここにいる。真実に直面する準備はできているか？",
    nameLabel: "名前は？",
    startBtn: "ストア派セッションを開始",
    dashboardGreeting: "こんにちは、{name}。",
    dashboardPrompt: "何があなたの心の平穏を乱しているのか？",
    inputPlaceholder: "ここに不安を書きなさい... 正直に。",
    imgAttached: "画像が添付されました",
    analyzeBtn: "論理を分析する",
    worstCaseBtn: "最悪のシナリオをシミュレート",
    loading: "マルクスが思考中...",
    resultTitle: "分析結果",
    filterTitle: "事実のフィルター",
    facts: "事実 (現実)",
    opinions: "意見 (認識)",
    dichotomyTitle: "管理の二分法",
    inControl: "あなたの力にあるもの",
    outControl: "あなたの力にないもの",
    verdictTitle: "マルクスの評決",
    debateBtn: "マルクスと議論する",
    doneBtn: "完了",
    debateHeader: "ストア派討論",
    debateOnline: "マルクス オンライン",
    debateEnd: "終了",
    debatePlaceholder: "マルクスの論理に挑戦する...",
    debateInit: "評決は下された。しかし、疑いがあるなら話せ。どの論理に異議があるのか？",
    error: "マルクスは沈黙している。接続またはAPIキーを確認して再試行してください。"
  },
  ES: {
    splashSub: "Lógica sobre el Caos",
    onboardingTitle: "No soy un amigo que te mimará.",
    onboardingDesc: "Estoy aquí para entrenar tu lógica. ¿Estás listo para enfrentar la verdad?",
    nameLabel: "¿Cuál es tu nombre?",
    startBtn: "INICIAR SESIÓN ESTOICA",
    dashboardGreeting: "Hola, {name}.",
    dashboardPrompt: "¿Qué perturba tu paz mental?",
    inputPlaceholder: "Escribe tu ansiedad aquí... Sé honesto.",
    imgAttached: "Imagen adjunta",
    analyzeBtn: "ANALIZAR LÓGICA",
    worstCaseBtn: "Simular el Peor Caso",
    loading: "Marco está pensando...",
    resultTitle: "El Análisis",
    filterTitle: "El Filtro",
    facts: "Hechos (Realidad)",
    opinions: "Opiniones (Percepción)",
    dichotomyTitle: "Dicotomía del Control",
    inControl: "En Tu Poder",
    outControl: "No En Tu Poder",
    verdictTitle: "Veredicto de Marco",
    debateBtn: "Debatir con Marco",
    doneBtn: "Hecho",
    debateHeader: "Debate Estoico",
    debateOnline: "Marco en línea",
    debateEnd: "Finalizar",
    debatePlaceholder: "Desafía la lógica de Marco...",
    debateInit: "El veredicto está dado. Pero si dudas, habla. ¿Qué lógica deseas desafiar?",
    error: "Marco está en silencio. Verifica tu conexión o clave API e intenta nuevamente."
  },
  DE: {
    splashSub: "Logik über Chaos",
    onboardingTitle: "Ich bin kein Freund, der dich verhätschelt.",
    onboardingDesc: "Ich bin hier, um deine Logik zu trainieren. Bist du bereit für die Wahrheit?",
    nameLabel: "Wie heißt du?",
    startBtn: "STOISCHE SITZUNG BEGINNEN",
    dashboardGreeting: "Hallo, {name}.",
    dashboardPrompt: "Was stört deinen Seelenfrieden?",
    inputPlaceholder: "Schreibe deine Angst hier nieder... Sei ehrlich.",
    imgAttached: "Bild angehängt",
    analyzeBtn: "LOGIK ANALYSIEREN",
    worstCaseBtn: "Worst-Case simulieren",
    loading: "Marcus denkt nach...",
    resultTitle: "Die Analyse",
    filterTitle: "Der Filter",
    facts: "Fakten (Realität)",
    opinions: "Meinungen (Wahrnehmung)",
    dichotomyTitle: "Dichotomie der Kontrolle",
    inControl: "In deiner Macht",
    outControl: "Nicht in deiner Macht",
    verdictTitle: "Marcus' Urteil",
    debateBtn: "Mit Marcus debattieren",
    doneBtn: "Fertig",
    debateHeader: "Stoische Debatte",
    debateOnline: "Marcus Online",
    debateEnd: "Beenden",
    debatePlaceholder: "Fordere Marcus' Logik heraus...",
    debateInit: "Das Urteil ist gefallen. Aber wenn du zweifelst, sprich. Welche Logik willst du anfechten?",
    error: "Marcus schweigt. Überprüfen Sie Ihre Verbindung oder Ihren API-Schlüssel."
  }
};
